apiVersion: v1
kind: Service
metadata:
  name: tcp-state
  labels:
    app: tcp-state
spec:
  ports:
  - port: 50051
    name: tcp-state
  clusterIP: None
  selector:
    app: tcp-state
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-state
spec:
  selector:
    matchLabels:
      app: tcp-state
  serviceName: "tcp-state"
  replicas: 1
  template:
    metadata:
      labels:
        app: tcp-state
    spec:
      containers:
      - name: tcp-state
        image: 239234376445.dkr.ecr.ap-northeast-2.amazonaws.com/grpc-server:server-2-v2
        ports:
        - containerPort: 50051
          name: tcp-state
